# Generated by Django 4.2.7 on 2023-11-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0004_remove_file_item_item_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='file',
            new_name='file_fk',
        ),
        migrations.AddField(
            model_name='file',
            name='item_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listapp.item'),
        ),
    ]
