# Generated by Django 4.2.7 on 2024-05-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listapp", "0008_remove_file_item_item_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "Female"), (1, "Male"), (2, "Unknown")], default=2
                    ),
                ),
                (
                    "age",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=7, null=True
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="cat")),
            ],
        ),
    ]
