# Generated by Django 4.2.7 on 2023-11-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listapp.file'),
        ),
    ]
