# Generated by Django 4.2.7 on 2023-11-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0005_rename_file_item_file_fk_file_item_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file_fk',
        ),
    ]
